server:
  port: 7910
spring:
  application:
    name: app-book

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    # 健康检查
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true